### ISSUE TITLE
Arguments

### ISSUE THREAD

**Issue by juliusspencer** [flutterings/flutter_redux_navigation#1]
Hi,

Is there a way to pass arguments in, when using the push method?

In the Navigator there is the possibility to do this:
https://docs.flutter.io/flutter/widgets/Navigator/pushNamed.html

Currently we're putting items on our store and then picking them up in our model.

Thanks for the help.

**Comment by esarbanis** [comment]
Hi @juliusspencer !

First of all thanks for using flutter_redux_navigation! 

This seems to be an easy addition both for `push` and `replace`, that will not break things. But just to be clear, you mean something like the following?

```dart
NavigateToAction.push('name', arguments: arguments);
NavigateToAction.replace('name', arguments: arguments);
```

**Comment by juliusspencer** [comment]
HI @esarbanis, yes, that's the idea. 

Do you know if flutter_redux_navigation can handle nested navigation?

**Comment by esarbanis** [comment]
Can you elaborate a bit on the nested navigation 🤔?

**Comment by juliusspencer** [comment]
Sure, it's described in the Navigator class documentation under **Nesting Navigators**:
https://docs.flutter.io/flutter/widgets/Navigator-class.html

**Comment by esarbanis** [comment]
@juliusspencer can you open up another issue for the nested navigation so that we can separate the two conversions?

**Comment by esarbanis** [comment]
@juliusspencer the arguments parameter is added in version 0.4.0 which is now [published](https://pub.dartlang.org/packages/flutter_redux_navigation) 😉
