### ISSUE TITLE
support for redux 4.0.0

### ISSUE THREAD

**Issue by abianche** [flutterings/flutter_redux_navigation#12]
is this package going to be updated to support redux 4.0.0 version?

**Comment by esarbanis** [comment]
We have an issue now, so it will 🙂

**Comment by sanisloandras** [comment]
Hi, I don't want to be mean, but can anybody provide some info when will we get the support for redux 4.0.0?

**Comment by esarbanis** [comment]
Hi @sanisloandras no need to be mean 🙂 things are underway

**Comment by esarbanis** [comment]
Redux 4.0.0 support is added to version 0.5.0
