### ISSUE TITLE
Navigation Called Twice

### ISSUE THREAD

**Issue by barak-innov** [flutterings/flutter_redux_navigation#16]
Hi,
first let me thank you for this library its really helpful.

When I run the following code:
```dart
store.dispatch(NavigateToAction.replace("/MainPage"));
```
the `MainPage` shown twice(built twice), its occur with the function `pushNamedAndRemoveUntil` too.

BUT if i run, in the same place the following code:
```dart
Navigator.pushAndRemoveUntil(
              context,
              MaterialPageRoute(builder: (context) => MainPage()),
              (Route<dynamic> route) => false,
            );
```

the `MainPage` shown just one time, as I expected.

What can I do?
Thanks,
Barak.

**Comment by esarbanis** [comment]
I am going to close this as it is really old and I really hope you found your answer by now. I am really sorry @barak-innov for not responding ...
