### ISSUE TITLE
Accessing route arguments from NavigatorHolder

### ISSUE THREAD

**Issue by Erfa** [flutterings/flutter_redux_navigation#17]
As far as I understand, the way to access the navigator state is not through the redux store, but instead from the global NavigatorHolder.

This works fine for the route name, but not for the arguments.

Say that you have this situation:
* You have a chat application where there is a `conversation` route with an `id` argument to indicate which chat you are in.
* You receive push notifications in a middleware for incoming messages
* When a message comes in, you want to check if you are in the `conversation` route with a specific `id`, and have different side-effects for messages coming to the current conversation as opposed to other conversations

I don't think there's an easy way of doing that right now. If I'm wrong I'd be happy to learn!

**Comment by esarbanis** [comment]
The fix was published as part of v0.6.0. Thanks for your help!
