### ISSUE TITLE
How to dispatch a navigation action during widget build?

### ISSUE THREAD

**Issue by Nimrodda** [flutterings/flutter_redux_navigation#19]
Navigating from widget tap action, etc. is working great, but when I dispatch an action in `StoreConnector.onInit`, which is then intercepted by a Middleware that dispatches a navigation action, I get an error that I can't navigate while the widget is being built. How can I overcome this issue?

**Comment by esarbanis** [comment]
Oh wow this issue is almost a year old! I am sorry @Nimrodda for not responding to this ... IDK if you found your answer, but I will close this issue now. Feel free to re-open if you still have this question.
