### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by jimmyff** [flutterings/flutter_redux_navigation#22]
Hey, this is one of the few packages my app depends on that doesn't yet support null safety, are you planning to update?

Thanks

**Comment by esarbanis** [comment]
@jimmyff yes, the code is already there, I just need to find the time to release. I will try to make it happen today.

I will keep you posted in this issue.

**Comment by esarbanis** [comment]
@jimmyff null safety landed on v0.7.0
