### ISSUE TITLE
Trouble with Flutter 2.8.0 

### ISSUE THREAD

**Issue by yan-064** [flutterings/flutter_redux_navigation#25]
Hello,

Since the upgrade in 2.8.0, I have this issue :
`flutter_redux_navigation-0.7.0/lib/src/navigation_middleware.dart:35:26: Error: 'NavigationDestination' is imported from both 'package:flutter/src/material/navigation_bar.dart' and 'package:flutter_redux_navigation/src/navigation_destination.dart'.
          this._setState(NavigationDestination(
                         ^^^^^^^^^^^^^^^^^^^^^
`

Now, there is a NavigationDestination class in the material lib and yours. Could you update by renaming your own NavigationDestination class ?

Thanks.

**Comment by leonardo2204** [comment]
I've just opened a PR fixing this issue: #26 
Hope it gets merged soon :D

**Comment by yan-064** [comment]
> I've just opened a PR fixing this issue: #26 Hope it gets merged soon :D

Thanks 👍, I hope too.

**Comment by maguon** [comment]
➕ 1⃣️
NavigationDestination is confilct with Flutter 2.8

**Comment by leonardo2204** [comment]
@esarbanis I think you forgot to release a new tag :D

**Comment by esarbanis** [comment]
@leonardo2204 didn't forget, I just run out of time :sweat_smile: I will though tomorrow :crossed_fingers:

**Comment by leonardo2204** [comment]
Ohh, ok! Sorry about that! Thanks for doing that

**Comment by MrObe13** [comment]
Hi, is there any news?

**Comment by esarbanis** [comment]
The fix landed in version 0.7.1
