### ISSUE TITLE
Wrong paths using navigation replace.

### ISSUE THREAD

**Issue by jpuerto** [flutterings/flutter_redux_navigation#4]
I have integrated the library and I have added a middleware that captures the NavigateToAction objects and print a console message about the current and previous path for every change. I have found an issue when using the replace and pop actions. As example see this navigation example:

Page 1 (push) Page 2 (replace) Page 3 (pop) Page 1

I expect that on the last transition, the current path is "Page 1" because I replaced "Page 2" with "Page 3" but with current implementation the value is "Page 2".

The problem is that the method "NavigationMiddleware._setState(String currentPath)" always takes the current path in the transition. For replace action the correct value should be the previous path as we are replacing.

**Comment by esarbanis** [comment]
I am going to close this as IDK the relevancy of it anymore.
