### ISSUE TITLE
Replacement for pushNamedAndRemoveUntil

### ISSUE THREAD

**Issue by stargazing-dino** [flutterings/flutter_redux_navigation#6]
Let me preface this by saying I'm very new to Flutter/Dart.

I'm trying to move a user from a login screen to the home screen. Once they're on the home screen I don't want them to go back either by pressing back on the phone or by using the appbar's back button.

In flutter, I found this did the trick:

```dart
onPressed: () => Navigator.pushNamedAndRemoveUntil(
      context,
      '/home',
      (Route<dynamic> route) => false,
    )
),
```

But I can't seem to find a replacement in this library. Is there anything I missed? or possibly a workaround? or would this be a whole new feature?

**Comment by esarbanis** [comment]
@Nolence you can find the new functionality in version 0.4.1 😉

**Comment by Nolence** [comment]
THanks @esarbanis! Appreciate your work on this library!

I'm having trouble knowing how the new functionality is used though. Do you simply import Material library and then do something like this inside your action?

```dart
store.dispatch(NavigateToAction.pushNamedAndRemoveUntil(
        '/home',
        (Route<dynamic> route) => false,
      ));
```

If so, it isn't really sending me anywhere. I go into my loading state for a bit and then after a few seconds  go back to a regular state. Here is my full action:

```dart
Future<String> loginAction(Store<AppState> store) async {
  store.dispatch(IsLoadingAction(true));

  try {
    GoogleSignInAccount _currentUser = await _googleSignIn.signIn();
    GoogleSignInAuthentication _googleAuth = await _currentUser.authentication;

    store.dispatch(LoginAction(_currentUser, _googleAuth));
    store.dispatch(NavigateToAction.pushNamedAndRemoveUntil(
      '/home',
      (Route<dynamic> route) => false,
    ));
    store.dispatch(IsLoadingAction(false));

    return '';
  } catch (error) {
    store.dispatch(AuthError(error.toString()));
    store.dispatch(IsLoadingAction(false));

    return error.toString();
  }
}
```
