### ISSUE TITLE
[Question] How do you override toString?

### ISSUE THREAD

**Issue by stargazing-dino** [flutterings/flutter_redux_navigation#8]
Sorry if this question is a little basic but how would I override the `toString` method on an action that I've imported? I have a logger middleware and I want it to show something like 
```sh
LoggingMiddleware: {Action: NavigateToAction - '/home' ...
````
instead of 
```sh
LoggingMiddleware: {Action: Instance of 'NavigateToAction'  ...
```

**Comment by esarbanis** [comment]
Hi @Nolence  I guess you could extend the `NavigationToAction` and override the `toString` there, which means that you have to use your custom action in your app.

On the other hand you can implement a `Logger` and and use it in the `LoggingMiddleware` to access `NavigationToAction`'s fields ( they are all public) in its log method to print out a more readable output.

**Comment by stargazing-dino** [comment]
Cool! Thanks @esarbanis. Right now I got it doing this (and using [this library](https://pub.dev/packages/redux_logging)):

```dart
String customLogFormatter<State>(
  State state,
  dynamic action,
  DateTime timestamp,
) {
  try {
    return "{Action: ${action.name}}";
  } catch (e) {
    return "{Action: $action}";
  }
}

var loggingMiddleware = LoggingMiddleware.printer(formatter: onlyLogActionFormatter),;
```

which seems sort of crazy to me but I don't know enough about null aware operators in dart to do it another way.
